#!/bin/bash


#
# export DISPLAY=`who | grep -m 1 \`whoami\` | sed s/.*\(// | sed s/\)//`:0 
# export DISPLAY=`who | grep $USER | tail -n 1 | sed -n '/(/,/)/{:a; $!N; /)/!{$!ba}; s/.*(\([^)]*\)).*/\1/p}'`
#
mytem=`tty | sed -e 's/\/dev\///g'`
display=`who | grep "$USER" | grep "$myterm" | sed -n '/(/,/)/{:a; $!N; /)/!{$!ba}; s/.*(\([^)]*\)).*/\1/p}'`
if [[ $display =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ || $display =~ ^([0-9a-fA-F]{0,4}:){1,7}[0-9a-fA-F]{0,4}$ ]]; then
    if [[ ! $display =~ ^(:[0-9]){1,2}$ ]]; then #filter out :x displays
        export DISPLAY="$display":0.0 
        echo "Setting DISPLAY to $DISPLAY"
    fi
fi

export LS_COLORS="ow=01;90:di=01;100" 

