#!/bin/bash

alias ct="cleartool"
alias bcomp="LD_LIBRARY_PATH=/usr/lib/beyondcompare /usr/lib/beyondcompare/BCompare"

alias snav="/opt/sourcenav/bin/snavigator"

#alias xterm="gnome-terminal"
alias grep="grep --color -In"
alias ll="ls -al"
alias tree="tree -apsDC"

alias regrep='f(){ grep -RE "$@" *; unset -f f; }; f'

export GDB=/opt/gdb163/bin/gdb
alias gdb163='f(){ /usr/bin/cgdb -d ${GDB:-/usr/bin/gdb} "$@"; unset -f f; }; f'
alias gdb='f(){ /usr/bin/cgdb -d /usr/bin/gdb "$@"; unset -f f; }; f'
alias rgdb='f(){ GLIBC_TUNABLES=glibc.cpu.hwcaps=-AVX,-AVX2,-AVX512BW,-AWX512DQ,-AVX512F,-AVX512VL,-BMI1,-BMI2,-LZCNT,-MOVBE,-RTM,-SSE4_1,-SSE4_2,-SSSE3 ${GDB:-/usr/bin/gdb} "$@"; unset -f f; }; f'

alias spin='f(){ if [ -f  /home/amelinte/work/Spin/Src/spin ]; then  /home/amelinte/work/Spin/Src/spin "$@" *; else  spin "$@" *; fi; unset -f f; }; f'
