#!/bin/bash

unamer=`uname -r`
if [[ ! "$unamer" =~ "microsoft" && ! "$unamer" =~ "WSL" ]]; then
    return 0
fi

WINDOWS_USER=$(/mnt/c/Windows/System32/cmd.exe /c 'echo %USERNAME%' | sed -e 's/\r//g')

alias _code="/mnt/c/Users/$WINDOWS_USER/AppData/Local/Programs/cursor/Cursor.exe"
alias _notepad="/mnt/c/Program Files/Notepad++/notepad++.exe"

