#!/bin/bash

alias ct="cleartool"
alias bcomp="LD_LIBRARY_PATH=/usr/lib/beyondcompare /usr/lib/beyondcompare/BCompare"

alias snav="/opt/sourcenav/bin/snavigator"

#alias xterm="gnome-terminal"
alias grep="grep --color -In"
alias ll="ls -al"
alias tree="tree -apsDC"

alias regrep='f(){ grep -RE "$@" *; unset -f f; }; f'

alias gdb163='f(){ /usr/bin/cgdb -d /opt/gdb163/bin/gdb "$@" *; unset -f f; }; f'
alias gdb='f(){ /usr/bin/cgdb -d /usr/bin/gdb "$@" *; unset -f f; }; f'

alias spin='f(){ if [ -f  /home/amelinte/work/Spin/Src/spin ]; then  /home/amelinte/work/Spin/Src/spin "$@" *; else  spin "$@" *; fi; unset -f f; }; f'
