#!/bin/bash

#
# Add to ~/.bashrc
# source ${HOME}/work/github/setup-tools/linux/config/bash/bashrc
#

export CUSTOMCFGROOT=${HOME}/work/github/setup-tools/linux/config

CONFIGDIR=${CUSTOMCFGROOT}/bash
. ${CONFIGDIR}/aliases
. ${CONFIGDIR}/display
. ${CONFIGDIR}/path
. ${CONFIGDIR}/ps1
. ${CONFIGDIR}/varia



# 
# 
# 


