#!/bin/bash

#
# Add to ~/.bashrc: 
# source ${HOME}/work/github/setup-tools/linux/config/bash/bashrc
#

function linkto() {
    src=$1
    tgt=$2

    if [ ! -e ${tgt} ]; then
        echo "Fixing .${tgt}"
        ln -s ${src} ${tgt}
    fi
}

export CUSTOMCFGROOT=${HOME}/work/github/setup-tools/linux/config

CONFIGDIR=${CUSTOMCFGROOT}/bash
. ${CONFIGDIR}/aliases
. ${CONFIGDIR}/display
. ${CONFIGDIR}/path
. ${CONFIGDIR}/ps1
. ${CONFIGDIR}/varia

if [ ! -e ${HOME}/.gdbinit ]; then
  echo "Fixing .gdbinit"
  ln -s ${CUSTOMCFGROOT}/gdb/gdbinit ${HOME}/.gdbinit
fi

if [ ! -e ${HOME}/.gitconfig ]; then
  echo "Fixing .gitconfig"
  ln -s ${CUSTOMCFGROOT}/gitconfig ${HOME}/.gitconfig
fi

if [ ! -e ${HOME}/.vimrc ]; then
  echo "Fixing .vimrc"
  ln -s ${CUSTOMCFGROOT}/vimrc ${HOME}/.vimrc
fi

# 
# 
# 


