#!/bin/bash


#
# export DISPLAY=`who | grep -m 1 \`whoami\` | sed s/.*\(// | sed s/\)//`:0 
# export DISPLAY=`who | grep $USER | tail -n 1 | sed -n '/(/,/)/{:a; $!N; /)/!{$!ba}; s/.*(\([^)]*\)).*/\1/p}'`
#
mytem=`tty | sed -e 's/\/dev\///g'`
display=`who | grep "$USER" | grep "$myterm" | sed -n '/(/,/)/{:a; $!N; /)/!{$!ba}; s/.*(\([^)]*\)).*/\1/p}'`
if [ "x$display" != "x:0" ] && [ "x$display" != "x" ]; then
    export DISPLAY="$display":0.0 #remote
    echo "Setting DISPLAY to $DISPLAY"
fi

export LS_COLORS="ow=01;90:di=01;100" 

