#!/bin/bash

alias ct="cleartool"
alias bcomp="LD_LIBRARY_PATH=/usr/lib/beyondcompare /usr/lib/beyondcompare/BCompare"

alias snav="/opt/sourcenav/bin/snavigator"

alias xterm="gnome-terminal"
alias grep="grep --color -In"
alias ll="ls -al"
alias tree="tree -apsDC"

