#!/bin/bash

#
# Collect .so modules known to be needed for core analysis
# This excludes Edge stuff.
#



tar cvzf _collect_dlls_result.tgz   \
    /usr/lib64/libffi.so.6          \
    /usr/lib64/libgio-2.0.so.0      \
    /usr/lib64/libglib-2.0.so.0     \
    /usr/lib64/libgobject-2.0.so.0  \
    /usr/lib64/libgmodule-2.0.so.0  \
    /usr/lib64/libselinux.so.1      \
    /lib64/libpthread.so.0          \
    /lib64/libpthread-*.so          \
    /lib64/libm.so.6                \
    /lib64/librt.so.1               \
    /lib64/libresolv.so.2           \
    /lib64/libc.so.6                \
    /lib64/libthread_db.so.1        \
    /lib64/libgcc_s.so.1            \
    /lib64/libdl.so.2               \
    /lib64/libnss_compat-*.so       \
    /lib64/libnss_files.so.2        \
    /lib64/ld-linux-x86-64.so.2     \
    /lib64/libnss_dns.so.2          \
    /lib64/libthread_db-1.0.so      \
    /lib64/libz.so.1

ls -l _collect_dlls_result.tgz

