#!/bin/bash

#
# http://stackoverflow.com/questions/2836330/is-there-a-way-to-inspect-the-current-rpath-on-linux
# http://unix.stackexchange.com/questions/22926/where-do-executables-look-for-shared-objects-at-runtime
# https://en.wikipedia.org/wiki/Rpath
# http://ftp.gnu.org/old-gnu/Manuals/ld-2.9.1/html_node/ld_3.html
#
# LD_RUN_PATH=/home/amelinte/data/builds/system_main_systest/pub/gen/bin/l64:/home/amelinte/data/builds/core_main_systest/pub/gen/bin/l64:/home/amelinte/data/builds/data_main_systest/pub/gen/bin/l64:/home/amelinte/data/builds/media_main_systest/pub/gen/bin/l64:/home/amelinte/data/builds/ininbuild_main_systest/pub/gen/bin/l64:/home/amelinte/data/builds/edge_main_systest/pub/gen/bin/l64:/home/amelinte/data/builds/bridge_main_systest/pub/gen/bin/l64
#

echo "--- objdump:"
objdump -a -x "$1" | grep RPATH
objdump -a -x "$1" | grep RUNPATH

echo "--- readelf"
readelf -d "$1" 
