#!/bin/bash

#
#
#

# export DISPLAY=`who | grep -m 1 \`whoami\` | sed s/.*\(// | sed s/\)//`:0 #Khaldoun
TTY=`tty | sed s=/dev/==`
export DISPLAY=`who | grep $USER | grep $TTY | sed -n '/(/,/)/{:a; $!N; /)/!{$!ba}; s/.*(\([^)]*\)).*/\1/p}'`
if [[ ! "$DISPLAY" =~ ":0" ]]; then
    export DISPLAY="$DISPLAY":0.0
fi

#override?
if [ "$#" -eq 1 ]; then
    echo "Forcing DISPLAY to $1" 
    export DISPLAY="$1":0.0
fi

echo "Setting DISPLAY to $DISPLAY"

