#!/bin/bash

#
#
#

ls ~/.local/share/cura/5.7/plugins/ > ~/work/github/setup-tools/linux/config/cura/plugins.txt

cp -pR /home/amelinte/.local/share/cura/5.7/definition_changes . || exit 1
cp -pR /home/amelinte/.local/share/cura/5.7/extruders          . || exit 1
cp -pR /home/amelinte/.local/share/cura/5.7/machine_instances  . || exit 1
cp -pR /home/amelinte/.local/share/cura/5.7/quality_changes    . || exit 1
cp -pR /home/amelinte/.local/share/cura/5.7/user               . || exit 1

echo "Done"
